# need to provide configuration
# if already is configured with mysql, password must be configured
server:
  port: 8082

spring:
  profiles:
    active: dev

---

spring:
  # profiles: dev
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: goodbyecruelworld
    url: jdbc:mysql://localhost:3306/onetoone-bi
    username: user
  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Crud application dev team
